channels:
- conda-forge
dependencies:
- python=3.10.18
- pip<=25.2
- pip:
  - mlflow==2.18.0
  - cloudpickle==1.6.0
  - numpy==1.26.4
  - pandas==2.3.3
  - psutil==7.0.0
  - pyarrow==18.1.0
  - scikit-learn==1.7.2
  - scipy==1.15.3
name: mlflow-env
